/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import javax.swing.JLayeredPane;
/**
 *
 * @author 20201194010010
 */
public class FormularioSistemaPousadas extends javax.swing.JFrame {

    /**
     * Creates new form FormSistemaPousadas
     */
    public FormularioSistemaPousadas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuSistema = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        menuCadastrar = new javax.swing.JMenu();
        miCadastrarCliente = new javax.swing.JMenuItem();
        miCadastrarQuarto = new javax.swing.JMenuItem();
        miCadastrarReserva = new javax.swing.JMenuItem();
        menuReservas = new javax.swing.JMenu();
        miExibirReservas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));

        menuSistema.setMnemonic('f');
        menuSistema.setText("Sistema");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Sair");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        menuSistema.add(exitMenuItem);

        menuBar.add(menuSistema);

        menuCadastrar.setMnemonic('e');
        menuCadastrar.setText("Cadastrar");

        miCadastrarCliente.setMnemonic('t');
        miCadastrarCliente.setText("Cliente");
        miCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastrarClienteActionPerformed(evt);
            }
        });
        menuCadastrar.add(miCadastrarCliente);

        miCadastrarQuarto.setMnemonic('y');
        miCadastrarQuarto.setText("Quarto");
        miCadastrarQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastrarQuartoActionPerformed(evt);
            }
        });
        menuCadastrar.add(miCadastrarQuarto);

        miCadastrarReserva.setMnemonic('p');
        miCadastrarReserva.setText("Reserva");
        miCadastrarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastrarReservaActionPerformed(evt);
            }
        });
        menuCadastrar.add(miCadastrarReserva);

        menuBar.add(menuCadastrar);

        menuReservas.setMnemonic('h');
        menuReservas.setText("Reservas");

        miExibirReservas.setMnemonic('c');
        miExibirReservas.setText("Reservas");
        menuReservas.add(miExibirReservas);

        menuBar.add(menuReservas);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void miCadastrarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastrarReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miCadastrarReservaActionPerformed

    private void miCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastrarClienteActionPerformed
        FormularioClientes formularioClientes = new FormularioClientes();
        desktopPane.add(formularioClientes, JLayeredPane.POPUP_LAYER);
        formularioClientes.setVisible(true);
    }//GEN-LAST:event_miCadastrarClienteActionPerformed

    private void miCadastrarQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastrarQuartoActionPerformed
        FormularioQuartos formularioQuartos = new FormularioQuartos();
        desktopPane.add(formularioQuartos, JLayeredPane.POPUP_LAYER);
        formularioQuartos.setVisible(true);
    }//GEN-LAST:event_miCadastrarQuartoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioSistemaPousadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioSistemaPousadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioSistemaPousadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioSistemaPousadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioSistemaPousadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenu menuReservas;
    private javax.swing.JMenu menuSistema;
    private javax.swing.JMenuItem miCadastrarCliente;
    private javax.swing.JMenuItem miCadastrarQuarto;
    private javax.swing.JMenuItem miCadastrarReserva;
    private javax.swing.JMenuItem miExibirReservas;
    // End of variables declaration//GEN-END:variables

}
